[project]
name = "users-data-generator"
version = "0.1.0"
description = "Generator for user data with Higyrus API integration"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.31.0",
    "python-dotenv>=1.0.0",
    "pydantic>=2.5.0",
    "pandas>=2.0.0",
]
